settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

# list of monitors
monitors:
  - id: trickey-solutions # unique identifier
    name: trickey.solutions
    description: 'Trickey Solutions Welcome Page. (umbraco site)' # default=empty
    url: 'https://trickey.solutions/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: porkeguess-trickey-solutions # unique identifier
    name: pokeguess.trickey.solutions
    description: 'S Pokemon Guessing Game' # default=empty
    url: 'https://pokeguess.trickey.solutions/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: monstermasher-trickey-solutions # unique identifier
    name: monstermasher.trickey.solutions
    description: 'Make your own monster' # default=empty
    url: 'https://monstermasher.trickey.solutions/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: ziggyzapper-trickey-solutions # unique identifier
    name: ziggyzapper.trickey.solutions
    description: 'Make your own monster' # default=empty
    url: 'https://ziggyzapper.trickey.solutions/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: namegame-trickey-solutions # unique identifier
    name: namegame.trickey.solutions
    description: 'Make your own monster' # default=empty
    url: 'https://namegame.trickey.solutions/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
